topic_expansion = {
    '18th century in games': ['19th century in games', 'Edmond Hoyle', 'Whist'],
    "1953 World Table Tennis Championships – Men's singles": ["1953 World Table Tennis Championships - Men's Singles", "1953 World Table Tennis Championships – Men's Singles", "1953 World Table Tennis Championships - Men's singles", '1926 World Table Tennis Championships', '1928 World Table Tennis Championships', '1929 World Table Tennis Championships', '1930 World Table Tennis Championships', '1931 World Table Tennis Championships', '1932 World Table Tennis Championships', '1933 World Table Tennis Championships (January)', '1934 World Table Tennis Championships', '1935 World Table Tennis Championships', '1936 World Table Tennis Championships', '1937 World Table Tennis Championships', '1938 World Table Tennis Championships', '1939 World Table Tennis Championships', '1947 World Table Tennis Championships', '1948 World Table Tennis Championships', '1949 World Table Tennis Championships', '1950 World Table Tennis Championships', '1951 World Table Tennis Championships', '1952 World Table Tennis Championships', "1952 World Table Tennis Championships – Men's singles", '1953 World Table Tennis Championships', '1954 World Table Tennis Championships', "1954 World Table Tennis Championships – Men's singles", '1955 World Table Tennis Championships', '1956 World Table Tennis Championships', '1957 World Table Tennis Championships', '1959 World Table Tennis Championships', '1961 World Table Tennis Championships', '1963 World Table Tennis Championships', '1965 World Table Tennis Championships', '1967 World Table Tennis Championships', '1969 World Table Tennis Championships', '1971 World Table Tennis Championships', '1973 World Table Tennis Championships', '1975 World Table Tennis Championships', '1977 World Table Tennis Championships', '1979 World Table Tennis Championships', '1981 World Table Tennis Championships', '1983 World Table Tennis Championships', '1985 World Table Tennis Championships', '1987 World Table Tennis Championships', '1989 World Table Tennis Championships', '1991 World Table Tennis Championships', '1993 World Table Tennis Championships', '1995 World Table Tennis Championships', '1997 World Table Tennis Championships', '1999 World Table Tennis Championships', '2000 World Team Table Tennis Championships', '2001 World Table Tennis Championships', '2003 World Table Tennis Championships', "1953 World Table Tennis Championships – Women's singles", "1957 World Table Tennis Championships – Men's singles", "1956 World Table Tennis Championships – Men's singles", "1950 World Table Tennis Championships – Men's singles", "1932 World Table Tennis Championships – Men's singles", "1926 World Table Tennis Championships – Men's singles", "1951 World Table Tennis Championships – Men's singles", "1931 World Table Tennis Championships – Men's singles", "1959 World Table Tennis Championships – Men's singles", "1930 World Table Tennis Championships – Men's singles", "1955 World Table Tennis Championships – Men's singles", "1928 World Table Tennis Championships – Men's singles", "1929 World Table Tennis Championships – Men's singles", "1965 World Table Tennis Championships – Men's singles", "1939 World Table Tennis Championships – Men's singles", "1937 World Table Tennis Championships – Men's singles", "1979 World Table Tennis Championships – Men's singles", "1997 World Table Tennis Championships – Men's singles", "1991 World Table Tennis Championships – Men's singles", "1999 World Table Tennis Championships – Men's singles", "1995 World Table Tennis Championships – Men's singles", "1934 World Table Tennis Championships – Men's singles"],
    '1966 Trinity Tigers football team': ['1966 Trinity Tigers football season', '1900 Trinity Tigers football team', '1901 Trinity Tigers football team', '1902 Trinity Tigers football team', '1903 Trinity Tigers football team', '1904 Trinity Tigers football team', '1905 Trinity Tigers football team', '1907 Trinity Tigers football team', '1908 Trinity Tigers football team', '1909 Trinity Tigers football team', '1910 Trinity Tigers football team', '1911 Trinity Tigers football team', '1912 Trinity Tigers football team', '1913 Trinity Tigers football team', '1914 Trinity Tigers football team', '1915 Trinity Tigers football team', '1916 Trinity Tigers football team', '1917 Trinity Tigers football team', '1918 Trinity Tigers football team', '1919 Trinity Tigers football team', '1920 Trinity Tigers football team', '1921 Trinity Tigers football team', '1922 Trinity Tigers football team', '1923 Trinity Tigers football team', '1924 Trinity Tigers football team', '1925 Trinity Tigers football team', '1926 Trinity Tigers football team', '1927 Trinity Tigers football team', '1928 Trinity Tigers football team', '1929 Trinity Tigers football team', '1930 Trinity Tigers football team', '1931 Trinity Tigers football team', '1932 Trinity Tigers football team', '1933 Trinity Tigers football team', '1934 Trinity Tigers football team', '1935 Trinity Tigers football team', '1936 Trinity Tigers football team', '1937 Trinity Tigers football team', '1938 Trinity Tigers football team', '1939 Trinity Tigers football team', '1940 Trinity Tigers football team', '1941 Trinity Tigers football team', '1946 Trinity Tigers football team', '1947 Trinity Tigers football team', '1948 Trinity Tigers football team', '1949 Trinity Tigers football team', '1950 Trinity Tigers football team', '1951 Trinity Tigers football team', '1952 Trinity Tigers football team', '1953 Trinity Tigers football team', '1954 Trinity Tigers football team', '1965 Trinity Tigers football team', '1968 Trinity Tigers football team', '1969 Trinity Tigers football team', '1967 Trinity Tigers football team', '1964 Trinity Tigers football team', '1970 Trinity Tigers football team', '1971 Trinity Tigers football team'],
    '1988 Australian Professional Championship': ['1987 Australian Professional Championship', '1988 Canadian Masters', '1988 Canadian Professional Championship', '1988 Dubai Masters', '1988 Fosters Professional', '1988 Grand Prix (snooker)', '1988 Hong Kong Masters', '1988 International Open', '1988 Matchroom Professional Championship', '1988 New Zealand Masters', '1988 Norwich Union Grand Prix', '1988 UK Championship', '1988 World Matchplay (snooker)', '1988–89 snooker season', '1989 British Open', '1989 Classic (snooker)', '1989 English Professional Championship', '1989 European Open (snooker)', '1989 Irish Masters', '1989 Irish Professional Championship', '1989 Kent Cup', '1989 London Masters', '1989 Masters (snooker)', '1989 Matchroom League', '1989 Pontins Professional', '1989 Scottish Professional Championship', '1989 South African Professional Championship', '1989 Welsh Professional Championship', '1989 World Cup (snooker)', '1989 World Snooker Championship', 'Australia', 'Australian Professional Championship', 'Australian dollar', 'Eddie Charlton', 'Glen Wilkinson', 'Greg Jenkins (snooker player)', 'Ian Anderson (snooker player)', 'James Giannaros', 'John Campbell (snooker player)', 'Lou Condo', 'Paddy Morgan', 'Robby Foldvari', 'Sam Frangie', 'Seed (sports)', 'Snooker world rankings', 'Sydney', 'The Sydney Morning Herald', 'Vladimir Potazsnyk', 'Warren King (snooker player)', 'World Professional Billiards and Snooker Association', '1972 Australian Professional Championship', '1978 Australian Professional Championship', '1984 Australian Professional Championship', '1986 Australian Professional Championship', '1985 Australian Professional Championship', '1976 Australian Professional Championship', '1977 Australian Professional Championship', '1975 Australian Professional Championship', '1966 Australian Professional Championship'],
    '1997 Welsh devolution referendum': ['Referendum on Welsh devolution', 'Wales referendum 1997', '1997 Wales referendum', 'Wales devolution referendum, 1997', 'Welsh referendum, 1997', '1997 Welsh Assembly referendum', 'Welsh devolution referendum, 1997', 'Wales referendum, 1997', '1802 United Kingdom general election in Wales', '1806 United Kingdom general election in Wales', '1807 United Kingdom general election in Wales', '1812 United Kingdom general election in Wales', '1818 United Kingdom general election in Wales', '1820 United Kingdom general election in Wales', '1826 United Kingdom general election in Wales', '1830 United Kingdom general election in Wales', '1831 United Kingdom general election in Wales', '1832 United Kingdom general election in Wales', '1835 United Kingdom general election in Wales', '1837 United Kingdom general election', '1837 United Kingdom general election in Wales', '1841 United Kingdom general election', '1841 United Kingdom general election in Wales', '1847 United Kingdom general election', '1847 United Kingdom general election in Wales', '1852 United Kingdom general election', '1852 United Kingdom general election in Wales', '1857 United Kingdom general election in Wales', '1859 United Kingdom general election', '1859 United Kingdom general election in Wales', '1865 United Kingdom general election', '1865 United Kingdom general election in Wales', '1868 United Kingdom general election', '1868 United Kingdom general election in Wales', '1874 United Kingdom general election', '1874 United Kingdom general election in Wales', '1880 United Kingdom general election', '1880 United Kingdom general election in Wales', '1885 United Kingdom general election in Wales', '1886 United Kingdom general election in Wales', '1892 United Kingdom general election in Wales', '1895 United Kingdom general election in Wales', '1900 United Kingdom general election in Wales', '1906 United Kingdom general election in Wales', '1915–1916 Church of England border polls', '1918 United Kingdom general election in Wales', '1922 United Kingdom general election in Wales', '1923 United Kingdom general election in Wales', '1924 United Kingdom general election in Wales', '1929 United Kingdom general election in Wales', '1931 United Kingdom general election in Wales', '1935 United Kingdom general election in Wales', '1945 United Kingdom general election in Wales', '1950 United Kingdom general election in Wales', '1951 United Kingdom general election in Wales', '1955 United Kingdom general election in Wales', '1959 United Kingdom general election in Wales', '1964 United Kingdom general election in Wales', '1979 Welsh devolution referendum'],
    '2014 NCAA Division II Football Championship Game': [],
    '2026 Shanghai Shenhua F.C. season': [],
    '469705 ǂKá̦gára': [],
    'Ahmed Romel': [],
    'Alexandru Marc': [],
    'Alfred Waterhouse': [],
    'Alpine Fortress': [],
    'American Civil War': ['American Civil War reenactment', 'List of American Civil War battles', 'American Civil War prison camps', 'American Civil War widows who survived into the 21st century', 'List of American Civil War generals', 'American Civil War corps badges', 'American Civil War alternate histories', 'American Civil War Museum', 'American Civil War spies', 'American Civil War Centennial', 'American Civil War: From Sumter to Appomattox', 'American Civil War battlefield preservation', 'American Civil War fortifications in Louisville', 'American Civil War union conscription', 'American Civil War Weapons', 'American Civil War nomenclature', 'American Civil War photography', 'American Civil War and women', 'American Civil War Bibliography', 'American Civil War blockade runners', 'American Civil War Memorial', 'American civil war surrender', 'American Civil War memory', 'American Civil War medicine'],
    'Ammonium hexaiodoplatinate(IV)': ['ACS Publications', "Adams' catalyst", 'Aluminon', 'Ammonium', 'Ammonium acetate', 'Ammonium adipate', 'Ammonium alginate', 'Ammonium alum', 'Ammonium arsenate', 'Ammonium azide', 'Ammonium benzoate', 'Ammonium bicarbonate', 'Ammonium bifluoride', 'Ammonium bisulfate', 'Ammonium bituminosulfonate', 'Ammonium bromate', 'Ammonium bromide', 'Ammonium butyrate', 'Ammonium calcium phosphate', 'Ammonium caprylate', 'Ammonium carbamate', 'Ammonium carbonate', 'Ammonium cerium(IV) sulfate', 'Ammonium chlorate', 'Ammonium chloride', 'Ammonium chromate', 'Ammonium cinnamate', 'Ammonium cyanate', 'Ammonium cyanide', 'Ammonium dichromate', 'Ammonium dicyanoaurate', 'Ammonium diethyl dithiophosphate', 'Ammonium dihydrogen arsenate', 'Ammonium dihydrogen phosphate', 'Ammonium ferric citrate', 'Ammonium fluoride', 'Ammonium fluorosilicate', 'Ammonium formate', 'Ammonium fumarate', 'Ammonium heptadecanoate', 'Ammonium heptamolybdate', 'Ammonium hexabromomercurate(II)', 'Ammonium hexabromoplatinate', 'Ammonium hexabromoselenate', 'Ammonium hexabromostannate(IV)', 'Ammonium hexachloroiridate(IV)', 'Ammonium hexachloroosmate(IV)', 'Ammonium hexachloropalladate', 'Ammonium hexachloroplatinate', 'Ammonium hexachloroplumbate'],
    'Android': ['Andriod', 'Android (disambiguation)', 'Andoid', 'Androd', 'Anroid', 'Adroid', 'Androi', 'Androdi', 'The Android', 'Androids (disambiguation)', 'Amazo', 'Android (board game)', 'Android (film)', 'Android (operating system)', 'Android (robot)', 'Android (song)', 'Android 17 (Dragon Ball)', 'Android 18', 'Android TV', 'Android mascot', 'App (film)', 'Cyborg', 'Dragon Ball Z: Super Android 13!', 'Droid (disambiguation)', 'Gynoid', 'Kerplunk (album)', 'Metalman (disambiguation)', 'Oxymetholone', 'Robot', 'Robotman (disambiguation)', 'The Android (novel)', 'The Androids', 'What Evil Lurks', 'Android version history', 'List of Android smartphones', 'Android 16', 'Android One', 'Android 10', 'Android: Netrunner', 'Android Nougat', 'Android Oreo', 'Android Lollipop', 'Android Marshmallow', 'Android Kunjappan Version 5.25', 'Android Team Awareness Kit', 'Android Jelly Bean', 'Android Studio', 'Android KitKat', 'Android Ice Cream Sandwich', 'Android Cupcake', 'Android software development', 'Android 13', 'Android 12'],
    'Anlaug Amanda Djupvik': ['Anlaug Amanda Kaas', 'Anlaug Djupvik', '32892 Prufrock', 'Astronomer', 'European Space Agency', 'Førde (town)', 'Førde Municipality', 'Gurskøya', 'Herøy Municipality (Møre og Romsdal)', 'Initial mass function', 'Kaare Aksnes', 'Leikong', 'Malcolm Fridlund', 'Minor planet', 'Noordwijk', 'Nordic Optical Telescope', 'Norges forskningsråd', 'Norway', 'Norwegian Research Council', 'Oslo', 'Roque de los Muchachos Observatory', 'Saltsjöbaden', 'Star formation', 'Stockholm Observatory', 'Wayback Machine', 'Ålesund'],
    'Anthony Flinn': [],
    'Arsala Khan': [],
    'Artificial intelligence': [],
    'Asparagus curillus': [],
    'Atilla Özmen': [],
    'Auster Aircraft': [],
    'Automaton': [],
    'Azatamut': [],
    'Berkeley station (Illinois)': [],
    'Bizarre magic': [],
    'Bless You (disambiguation)': ['Blessy (disambiguation)'],
    'Bob Starr (sportscaster)': [],
    'Bournemouth': ['Bournemouth Airport', 'Bournemouth, Christchurch and Poole Council', 'Bournemouth University', 'Bournemouth Symphony Orchestra', 'Bournemouth West', 'Bournemouth East', 'Bournemouth, Christchurch and Poole Council elections', 'Bournemouth Borough Council elections', 'Bournemouth, Christchurch and Poole', 'Bournemouth School', 'Bournemouth Air Festival', 'Bournemouth and Poole College', 'Bournemouth Bobcats', 'Archdeacon of Bournemouth', 'Bournemouth railway station', 'Bournemouth Reform Synagogue', 'Bournemouth F.C.', 'Bournemouth School for Girls', 'Bournemouth Gasworks Athletic F.C.', 'Bournemouth Gardens, England', 'Bournemouth Collegiate School', 'Bournemouth Aviation Museum', 'Bournemouth Sports F.C.', 'Bournemouth Water'],
    'Brazen head': [],
    'Brittney Miller': [],
    'Butch Booker': [],
    'Büro, Büro': [],
    'Cardistry': [],
    'Carl Johan Ege': [],
    'Carl Stough': [],
    'Catatonia (band)': [],
    "Centre International de la Mécanique d'Art": [],
    'Chadbourn Spanish Gospel Mission': [],
    'Chalarotona intabescens': [],
    'Chambon-sur-Cisse': [],
    'Chinese mathematics': [],
    'Chronology of the Great Famine': [],
    'Claddagh': [],
    'Collagen triple helix repeat containing 1': [],
    'Counterweight': [],
    'Counts of Berga': [],
    'Ctesibius': [],
    'Cyborg': [],
    'Deutsch-Wagram': [],
    'Droid (disambiguation)': [],
    'EMLL 38th Anniversary Show': ['EMLL 50th Anniversary Show', 'EMLL 36th Anniversary Show', 'EMLL 48th Anniversary Show', 'EMLL 39th Anniversary Show (2)', 'EMLL 56th Anniversary Show', 'EMLL 37th Anniversary Show', 'EMLL 30th Anniversary Show (2)', 'EMLL 47th Anniversary Show', 'EMLL 54th Anniversary Show', 'EMLL 49th Anniversary Show', 'EMLL 46th Anniversary Show', 'EMLL 45th Anniversary Show', 'EMLL 19th Anniversary Show', 'EMLL 39th Anniversary Show (1)', 'EMLL 35th Anniversary Show', 'EMLL 4th Anniversary Show', 'EMLL 30th Anniversary Show (1)', 'EMLL 11th Anniversary Show', 'EMLL 57th Anniversary Show', 'EMLL 34th Anniversary Show', 'EMLL 12th Anniversary Show', 'EMLL 17th Anniversary Show', 'EMLL 15th Anniversary Show', 'EMLL 58th Anniversary Show'],
    'English ship Merlin (1652)': ['Merlin (1652)', 'HMS Merlin (1652)', '1650 Programme Group', '1651 Programme Group', '1652 Programme Group', "Builder's Old Measurement", 'Chatham Dockyard', 'Commonwealth of England', 'English ship Antelope (1652)', 'English ship Bristol (1653)', 'English ship Diamond (1652)', 'English ship Drake (1652)', 'English ship Laurel (1651)', 'English ship Martin (1652)', 'English ship Mermaid (1651)', 'English ship Nightingale (1651)', 'English ship Pearl (1651)', 'English ship Primrose (1651)', 'English ship Ruby (1652)', 'English ship Sapphire (1651)', 'Full-rigged ship', 'HMS Merlin', 'ISBN (identifier)', 'List of frigate classes of the Royal Navy', 'Sixth rate'],
    'Esther Nelson': ['Arthur William Moore', 'Ayre', 'Bride (parish)', 'Esther Nelson Karn', 'John Milton', 'Jurby', 'Manx National Heritage', 'Manx people', 'Napoleon', 'Rectory', 'Saint Helena', 'Santon, Isle of Man', "St. Patrick's Church, Jurby", 'Thomas Edward Brown', 'Wayback Machine', 'William Cubbon', 'Esther Newton', 'Esther Helton-Haynes', 'Esther Wilson', 'Esther Nielsen Vagning', 'Esther Deason Shield'],
    'Eucalyptus effusa': ['Rough-barked gimlet', 'Desert gimlet', 'Australian Plant Census', 'Australian Plant Name Index', 'Balladonia, Western Australia', 'Binomial nomenclature', 'Botanist', 'Capsule (botany)', 'Catalogue of Life', 'Coolgardie (biogeographic region)', 'Coppice', 'Department of Biodiversity, Conservation and Attractions', 'Department of Parks and Wildlife (Western Australia)', 'Doi (identifier)', 'Encyclopedia of Life', 'Endemism', 'Eucalyptus', 'Eucalyptus campaspe', 'Eucalyptus creta', 'Eucalyptus diptera', 'Eucalyptus jimberlanica', 'Eucalyptus ravida', 'Eucalyptus salubris', 'Eucalyptus terebra', 'Eucalyptus tortilis', 'Eudicots', 'FloraBase', 'Flora of Australia', 'Flowering plant', 'George Chippendale', 'Gimlet (eucalypt)', 'Global Biodiversity Information Facility', 'IBRA', 'INaturalist', 'ISBN (identifier)', 'IUCN Red List', 'Ian Brooker', 'Interim Register of Marine and Nonmarine Genera', 'International Plant Names Index', 'Ken Hill (botanist)', 'Lawrence Alexander Sidney Johnson', 'Lignotuber', 'List of Eucalyptus species', 'Mallee (habit)', 'Myrtaceae', 'Myrtales', 'National Center for Biotechnology Information', 'Norseman, Western Australia', 'Nullarbor Plain', 'Nuytsia (journal)', 'Open Tree of Life', 'Operculum (botany)'],
    'Evan Davies': [],
    'Evgeniya Brik': [],
    'Exposure (magic)': [],
    'First inversion': [],
    'Fisheries Research': [],
    'Fortune teller machine': [],
    'Fred Sington': [],
    'George Campbell Sherrin': [],
    'Gerald Cassidy (lobbyist)': [],
    'Giles Walker': ['Giles Waterfield', 'Giles Calvert', 'Glen Walker', 'Gale Stalker'],
    'Gordon Rorke': [],
    'Gordon Steege': [],
    'Gynoid': [],
    'HMS Pickle (1800)': [],
    'Hermann Nothnagel': [],
    'Horistus': [],
    'Ihor Buryak': [],
    'Jack Craggs': [],
    'Jack Hannagan': [],
    'John Craggs': [],
    'John Craggs (footballer)': [],
    'John Craggs (songwriter)': [],
    'John Hodgkin (barrister)': [],
    'Jonathan Edwards (English footballer)': [],
    'Joseph and Sarah Puterbaugh Farm': [],
    'Kadiria': [],
    'Keo Saphal (Siem Reap politician)': [],
    'Kingdom Come (Rebecca St. James album)': [],
    'Kourtsevo': [],
    'Lady Eli': [],
    'Letting Go (Suzy Bogguss song)': [],
    'Limay (disambiguation)': [],
    'List of Billboard Smooth Jazz Airplay number-ones of 2023': [],
    "List of Bishop's College School alumni": [],
    'List of elections in 1881': ['1881 Chilean presidential election', '1881 French legislative election', '1881 German federal election', '1881 Liberian general election', '1881 New York state election', '1881 New Zealand general election', '1881 Portuguese legislative election', '1881 Quebec general election', '1881 Spanish general election', '2001 electoral calendar', '2002 electoral calendar', '2003 electoral calendar', '2004 electoral calendar', '2005 electoral calendar', '2006 electoral calendar', '2007 electoral calendar', '2008 electoral calendar', '2009 electoral calendar', '2010 local electoral calendar', '2010 national electoral calendar', '2010 supranational electoral calendar', '2011 local electoral calendar', '2011 national electoral calendar', '2011 supranational electoral calendar', '2012 local electoral calendar', '2012 national electoral calendar', '2012 supranational electoral calendar', '2013 local electoral calendar', '2013 national electoral calendar', '2013 supranational electoral calendar', '2014 local electoral calendar', '2014 national electoral calendar', '2014 supranational electoral calendar', '2015 local electoral calendar', '2015 national electoral calendar', '2015 supranational electoral calendar', '2016 local electoral calendar', '2016 national electoral calendar', '2016 supranational electoral calendar', '2017 local electoral calendar', '2017 national electoral calendar', '2017 supranational electoral calendar', '2018 local electoral calendar', '2018 national electoral calendar', '2018 supranational electoral calendar', '2019 local electoral calendar', '2019 national electoral calendar', '2019 supranational electoral calendar', '2020 local electoral calendar', '2020 national electoral calendar', 'List of elections in 1980', 'List of elections in 1986', 'List of elections in 1991', 'List of elections in 1988', 'List of elections in 1971', 'List of elections in 1982', 'List of elections in 1984', 'List of elections in 1989', 'List of elections in 1987', 'List of elections in 1983', 'List of elections in 1865', 'List of elections in 1981', 'List of elections in 1919', 'List of elections in 1897', 'List of elections in 1899', 'List of elections in 1892', 'List of elections in 1912', 'List of elections in 1931', 'List of elections in 1985', 'List of elections in 1916', 'List of elections in 1941', 'List of elections in 1860', 'List of elections in 1918', 'List of elections in 1914'],
    'List of fictional robots and androids': ['Robots in television', 'List of fictional robots', 'List of fictional androids', 'Famous Fictional Robots', 'List of fictional robots & androids', 'Robots in science fiction', 'エッグロボ', "'80s Robot", '1X Technologies', '2000 AD (comics)', '2401 Penitent Tangent', '2B (Nier: Automata)', '3-D Struction', '343 Guilty Spark', '790 (robot)', '9 (2009 animated film)', 'A.I. Artificial Intelligence', 'A.I. Rising', 'A.P.E.X.', 'A.X.L.', 'ABB', 'ABC Warriors', 'AI takeover in popular culture', 'ASIMO', 'A Clever Dummy', 'A Scooby-Doo! Christmas', 'A Scooby-Doo Halloween', 'A Tale of Time City', 'A Terrifying Round with a Menacing Metallic Clown', 'Actroid', 'Adam Link', 'Adaptable robotics', 'Adventures of Sonic the Hedgehog', 'Aerobot', "Aesop's Fables (film series)", 'Africanfuturism', 'Afrofuturism', 'AgiBot', 'Agility Robotics', 'Agricultural robot', 'Ai-Da', 'Aigis (Persona)', 'Akademia pana Kleksa (novel)', 'Al Pacino', 'Albert (comics)', 'Alberto Camerini', 'Albion (comics)', 'Alien: Covenant', 'Alien (film)', 'Alien 3', 'Alien Resurrection', 'Alien invasion', 'Alien language', 'Aliens (film)', 'Alisa Bosconovitch', 'Alison Prince', "All's Fair at the Fair"],
    'List of magic museums': ['Academy of Magical Arts', 'American Museum of Magic', 'Appleton, Wisconsin', 'Associated Press', 'Australian Society of Magicians', 'Automaton', 'Balkans', 'Barcelona, Spain', 'Beverly, Massachusetts', 'Bizarre magic', 'Brazil', 'Brotherhood of Auckland Magicians', 'Brussels, Belgium', 'CBS News', 'Caesars Palace', 'Cagliari, Italy', 'Canada', 'Cape Town', 'Card manipulation', 'Cardistry', 'Cherasco (CN), Italy', "Children's magic", 'Chinese Water Torture Cell', 'Château de Blois', 'Clifton Hill (Niagara Falls)', 'Close-up magic', 'Coin magic', 'Coins through table', 'College of Magic', 'Conjuring (book)', 'Conjuring Arts Research Center', 'David Copperfield (illusionist)', 'Ephemera', 'Escapology', 'Exposure (magic)', 'Facebook', 'Famous Players–Lasky', 'Farmington Hills, Michigan', 'Forcing (magic)', 'Fruška Gora', 'Fédération Française des Artistes Prestidigitateurs', 'Fédération Internationale des Sociétés Magiques', 'Genii (magazine)', 'Glossary of magic (illusion)', "Goodliffe's Abracadabra", 'Gospel magic', 'Guinness Book of World Records', 'Guinness World Records', 'Harlem', 'Harry Blackstone, Jr.', 'List of music museums'],
    'Love tester machine': [],
    'Magic 8 Ball': [],
    'Magic mirror': [],
    "Maillardet's automaton": [],
    'Manuel de Noronha': [],
    'Marcel Hansen (criminal)': [],
    "Marvin's Marvelous Mechanical Museum": [],
    'Mason Redman': [],
    'Mechanical toy': [],
    'Michael R. Lerner': [],
    'Monaco at the 2011 World Championships in Athletics': [],
    'NGC 3200': [],
    'Naoki Hiraoka': [],
    'Nikolai Kozlenya': [],
    'Norman Lee': [],
    'Orontobates': [],
    'Peaceful Peters': [],
    'Polystichum californicum': [],
    'Programadora': [],
    'Pullback motor': [],
    'Republic of China Armed Forces Reserve': [],
    'Results of the 1938 South Australian state election (House of Assembly)': [],
    'River Cover': [],
    'Rupert Friend': [],
    'Răzvan Popa': [],
    'Sarangpur railway station': [],
    'Sarband, Bandar Abbas': [],
    'Sathinee Chankrachangwong': ['Satinee Jankrajangwong'],
    'Savart wheel': [],
    'Serhetabat': [],
    'Singing bird box': [],
    'Six Melodies (Cage)': ['27 minutes 10.554 seconds', '4′33″', 'A Flower', 'A Year from Monday', 'Apartment House 1776', 'As Slow as Possible', 'Bow (music)', 'But What About the Noise ...', 'Cheap Imitation', 'Classical music', 'Construction (Cage)', 'Crete Cage', 'Empty Words', 'Etudes Australes', 'Etudes Boreales', 'Europeras', 'Foundation for Contemporary Arts', 'Freeman Etudes', 'HPSCHD', 'Harmony', 'ISBN (identifier)', 'Imaginary Landscape', 'Imaginary Landscape No. 1', 'Imaginary Landscape No. 2 (March No. 1)', 'Imaginary Landscape No. 3', 'Imaginary Landscape No. 4 (March No. 2)', 'Imaginary Landscape No. 5', 'Indeterminacy (music)', 'Internet Archive', 'John Cage', 'Keyboard instrument', 'List of compositions by John Cage', 'Living Room Music', 'M (John Cage book)', 'Music for an Aquatic Ballet', 'Music of Changes', 'Musical composition', 'Notations', 'Number Pieces', 'Roaratorio', 'Silence: Lectures and Writings', 'Sonatas and Interludes', 'Song Books (Cage)', 'String Quartet in Four Parts', 'The Revenge of the Dead Indians', 'The Seasons (Cage)', 'The Wonderful Widow of Eighteen Springs', 'Variations (Cage)', 'Variations VII', 'Vibrato'],
    'Son of India': ['Son of India (disambiguation)', 'Son of India (film)', 'Son of India (1931 film)', 'Son of India (1962 film)', 'Son of India (2021 film)', 'Son of India (2022 film)', 'Son of Ingagi', 'Song of India (film)', 'Song of India (song)', 'Son of Iniquity', 'Songs Of India', 'Sino-Indian War', 'Sino-Indian border dispute', 'Sony India', 'Song of India', 'Soo Indians', 'Songlindian', 'Sino-Indian skirmish (2020)', 'Sanofi India', 'Sino-Indian relation', 'Sino Indian border', 'Sino-Indian cuisine', 'Sonic (Indian TV channel)', 'Sino-Indian skirmish (1967)', 'Soo Indians (NOJHL)', 'Sino-Indian skirmish (1987)', 'The Song of the Indian Wars'],
    'Strength tester machine': ['American Pickers', 'American Restoration', 'Amusement park', 'Bowling alley', 'Electric shock', 'Eurocom', 'Family entertainment center', 'Fortune teller machine', 'Framingham, Massachusetts', 'Game', 'High striker', 'LCD', 'Love tester machine', 'Musée Mécanique', 'Nightclub', 'Penny arcade', 'Physical strength', 'Pub', 'Punching bag', 'Redemption game', 'Santa Monica Pier', 'Sega', 'The New Addams Family', 'Video arcade', 'Video game'],
    'Stuart Carolan': [],
    'Suzanne Borel': [],
    'Sylvia Nooij': [],
    'Taxi Ramudu': [],
    'Teraphim': [],
    'The writing hand': [],
    'Thomas Thompson (American author)': [],
    'Thousands Are Sailing': [],
    'Tiina Intelmann': [],
    'Tonewheel': [],
    'Tony Bova': [],
    'Turks in Japan': [],
    'USS SC-131': [],
    'United States Medical Center for Federal Prisoners': [],
    'Utair Flight 579': [],
    'Valerian Pidmohylny': [],
    "Visheh Sara, Sowme'eh Sara": [],
    'Welland (Kettering BC Ward)': [],
    'Wind-up doll joke': [],
    'Wind-up toy': [],
    'You Disappear': [],
    'Zakir Baghirov (minister)': [],
    'Zara DuPont': [],
    'Zhang Tielin': [],
}
